name: Build BC-SGM

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Instalar Tauri CLI
        run: npm install -g @tauri-apps/cli

      - name: Compilar aplicativo
        run: npm run build
