name: Build BC-SGM

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Compilar aplicativo Tauri
        run: run: npm run build

      - name: Salvar executável
        uses: actions/upload-artifact@v4
        with:
          name: BC-SGM-BUILD
          path: src-tauri/target/release/*.exe
